"""Shared enumerations and result status values.

Confidence, risk and reputation are intentionally separate.
Never treat an inference as CONFIRMED.
"""

from __future__ import annotations

from enum import StrEnum


class EntityType(StrEnum):
    PERSON = "PERSON"
    USERNAME = "USERNAME"
    EMAIL = "EMAIL"
    DOMAIN = "DOMAIN"
    IP = "IP"
    URL = "URL"
    HASH = "HASH"
    PHONE = "PHONE"
    COMPANY = "COMPANY"
    ASN = "ASN"
    CERTIFICATE = "CERTIFICATE"
    DNS_RECORD = "DNS_RECORD"
    SOCIAL_PROFILE = "SOCIAL_PROFILE"
    FILE = "FILE"
    TECHNOLOGY = "TECHNOLOGY"
    SERVICE = "SERVICE"
    BREACH = "BREACH"
    THREAT = "THREAT"
    MALWARE = "MALWARE"
    REPOSITORY = "REPOSITORY"
    ORGANIZATION = "ORGANIZATION"
    SUBDOMAIN = "SUBDOMAIN"
    PUBLIC_MENTION = "PUBLIC_MENTION"


class Confidence(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CONFIRMED = "CONFIRMED"


class RiskLevel(StrEnum):
    LOW = "LOW"
    SUSPICIOUS = "SUSPICIOUS"
    HIGH_RISK = "HIGH_RISK"
    CONFIRMED_BY_PROVIDER = "CONFIRMED_BY_PROVIDER"


class FindingStatus(StrEnum):
    FOUND = "FOUND"
    NOT_FOUND = "NOT_FOUND"
    NOT_CONFIGURED = "NOT_CONFIGURED"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    INFERENCE = "INFERENCE"
    ERROR = "ERROR"
    SKIPPED = "SKIPPED"
    AUTHORIZATION_REQUIRED = "AUTHORIZATION_REQUIRED"
    INCONCLUSIVE = "INCONCLUSIVE"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    BLOCKED = "BLOCKED"
    RATE_LIMITED = "RATE_LIMITED"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    CHALLENGE_REQUIRED = "CHALLENGE_REQUIRED"
    CAPTCHA_REQUIRED = "CAPTCHA_REQUIRED"
    TEMPORARILY_LIMITED = "TEMPORARILY_LIMITED"
    OAUTH_BROWSER_REJECTED = "OAUTH_BROWSER_REJECTED"
    # Public mention/reference. Not account-found. Not a username LIKELY substitute.
    OBSERVED = "OBSERVED"


class UsernameCheckStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    LIKELY = "LIKELY"
    NOT_FOUND = "NOT_FOUND"
    INCONCLUSIVE = "INCONCLUSIVE"
    BLOCKED = "BLOCKED"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    RATE_LIMITED = "RATE_LIMITED"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    CHALLENGE_REQUIRED = "CHALLENGE_REQUIRED"
    CAPTCHA_REQUIRED = "CAPTCHA_REQUIRED"
    TEMPORARILY_LIMITED = "TEMPORARILY_LIMITED"
    OAUTH_BROWSER_REJECTED = "OAUTH_BROWSER_REJECTED"


class AccessMode(StrEnum):
    """How a public finding was collected. Authenticated ≠ private access."""

    ANONYMOUS_PUBLIC = "ANONYMOUS_PUBLIC"
    AUTHENTICATED_PUBLIC = "AUTHENTICATED_PUBLIC"


class SessionStatus(StrEnum):
    NOT_CONFIGURED = "NOT_CONFIGURED"
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    CHALLENGE_REQUIRED = "CHALLENGE_REQUIRED"
    CAPTCHA_REQUIRED = "CAPTCHA_REQUIRED"
    BLOCKED = "BLOCKED"
    TEMPORARILY_LIMITED = "TEMPORARILY_LIMITED"
    OAUTH_BROWSER_REJECTED = "OAUTH_BROWSER_REJECTED"
    CHROME_NOT_FOUND = "CHROME_NOT_FOUND"
    CDP_UNAVAILABLE = "CDP_UNAVAILABLE"
    CHROME_PROFILE_LOCKED = "CHROME_PROFILE_LOCKED"
    WINDOWS_CDP_LAUNCH_FAILED = "WINDOWS_CDP_LAUNCH_FAILED"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    UNAVAILABLE = "UNAVAILABLE"


class CacheState(StrEnum):
    LIVE = "LIVE"
    CACHED = "CACHED"
    REFRESHED = "REFRESHED"


class AuthPlatform(StrEnum):
    INSTAGRAM = "instagram"
    FACEBOOK = "facebook"
    THREADS = "threads"
    TIKTOK = "tiktok"
    X = "x"
    TWITCH = "twitch"


class AuthCapability(StrEnum):
    """How SPECTRE may authenticate for public OSINT. Not a bypass menu."""

    PLAYWRIGHT_SESSION = "PLAYWRIGHT_SESSION"
    CHROME_CDP_SESSION = "CHROME_CDP_SESSION"
    OFFICIAL_API = "OFFICIAL_API"
    BOTH = "BOTH"
    UNSUPPORTED = "UNSUPPORTED"


class ProviderKeyType(StrEnum):
    KEYLESS = "KEYLESS"
    OPTIONAL_API_KEY = "OPTIONAL_API_KEY"
    REQUIRED_API_KEY = "REQUIRED_API_KEY"


class RelationType(StrEnum):
    FOUND_ON = "FOUND_ON"
    RESOLVES_TO = "RESOLVES_TO"
    HOSTED_ON = "HOSTED_ON"
    BELONGS_TO_ASN = "BELONGS_TO_ASN"
    USES_EMAIL = "USES_EMAIL"
    USES_USERNAME = "USES_USERNAME"
    REFERENCES = "REFERENCES"
    HAS_CERTIFICATE = "HAS_CERTIFICATE"
    HAS_SUBDOMAIN = "HAS_SUBDOMAIN"
    OBSERVED_BY = "OBSERVED_BY"
    LINKS_TO = "LINKS_TO"
    REGISTERED_BY = "REGISTERED_BY"
    USES_NAMESERVER = "USES_NAMESERVER"
    USES_TECHNOLOGY = "USES_TECHNOLOGY"
    HAS_MX = "HAS_MX"
    BELONGS_TO_DOMAIN = "BELONGS_TO_DOMAIN"
    POSSIBLE_MATCH = "POSSIBLE_MATCH"
    HAS_PROFILE = "HAS_PROFILE"
    IDENTITY_LINK = "IDENTITY_LINK"
    OPERATOR_PROVIDED_ALIAS = "OPERATOR_PROVIDED_ALIAS"
    OPERATOR_PROVIDED_INPUT = "OPERATOR_PROVIDED_INPUT"


class InvestigationMode(StrEnum):
    PASSIVE = "PASSIVE_OSINT"
    ACTIVE_AUTHORIZED = "ACTIVE_RECON_AUTHORIZED"
